name: "add-to-projects"
author: "dev-hato Development Team"
description: "PRやIssueをGitHub Projectsに追加する"
inputs:
  github-token: # id of input
    description: "GITHUB_TOKEN"
    required: true
  project-url:
    description: "GitHub Projects URL"
    required: true
runs:
  using: "composite"
  steps:
    - name: Remove pull requests and issues from project
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        PROJECT_URL: ${{ inputs.project-url }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const {script} = require('${{ github.action_path }}/dist/remove_prs_and_issues.js')
          await script(github)
    - uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e # v1.0.2
      with:
        project-url: ${{ inputs.project-url }}
        github-token: ${{ inputs.github-token }}
