---
name: create-release
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/create-release.yml
      - dist/**
      - action.yml
permissions:
  contents: write
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: dev-hato/actions-create-release@3af1d4502c5f308357c7c14cb4436cc3aacbedd3 # v0.0.58
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
