name: Remove Tasks from Task List

on:
  pull_request:

jobs:
  rm-task-from-list:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.6.0
        with:
          app_id: ${{ secrets.PROJECT_AUTOMATION_APP_ID }}
          private_key: ${{ secrets.PROJECT_AUTOMATION_PRIVATE_KEY }}
      - name: Remove item
        id: get_latest_app_engine_support_version
        uses: actions/github-script@v6.2.0
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          result-encoding: string
          script: |
            const res = await github.graphql(`
              {
                organization(login: "dev-hato") {
                  projectV2(number: 1) {
                    id
                    items(first: 50) {
                      totalCount
                      pageInfo {
                        hasNextPage
                        endCursor
                      }
                      nodes {
                        id
                        content {
                          ... on PullRequest {
                            url
                            closed
                          }
                          ... on Issue {
                            url
                            closed
                          }
                        }
                      }
                    }
                  }
                }
              }
            `)
            console.log(res.organization.projectV2.id)
            console.log(res.organization.projectV2.items.totalCount)
            for (const item of res.organization.projectV2.items.nodes) {
              console.log(item.id)
              console.log(item.content.url)
              console.log(item.content.closed)
            }
